version: "2"
services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment: 
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
    networks: 
      worker_net:
        ipv4_address: 172.16.0.2
  woker:
    hostname: worker
    build:
      context: .
      dockerfile: dockerfile
    volumes: 
      - .:/app
    depends_on:
      - rabbit
    entrypoint: celery -A crawler.tasks worker -Q default,parsing
    networks:
      - worker_net
  downloader:
    hostname: downloader
    build:
      context: .
      dockerfile: dockerfile
    volumes: 
      - .:/app
    depends_on:
      - rabbit
    entrypoint: celery -A crawler.tasks worker -Q download --concurrency=20
    networks:
      - worker_net
networks:
    worker_net:
        driver: bridge
        ipam:
            config:
            - subnet: 172.16.0.0/24



    
